version: '3.4'
services:
  student-server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
    # flask vars
     - FLASK_HOST=0.0.0.0
     - FLASK_PORT=5000
     - FLASK_APP=app.py
     - FLASK_DEBUG=1
     - CHOKIDAR_USEPOLLING=true
  student-client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
